apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: selfheal-agent
  namespace: monitoring
  labels:
    app: selfheal-agent
    release: prometheus
spec:
  # Scraping services in the kube-system namespace
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      component: selfheal-cp
  endpoints:
    - port: metrics
      interval: 5s
      path: /metrics
      honorLabels: true
